from typing import Protocol

from pydantic import BaseModel

from .. import types
from . import transaction


# ======================================================================================================================
class MetadataStoreError(Exception):
    pass


# ======================================================================================================================
class MetadataConflictError(MetadataStoreError):
    # a commit's declared changes no longer match the current mapping — another commit landed in the meantime
    pass


# ======================================================================================================================
# one page of a directory listing: the files directly under a prefix and the distinct immediate subdirectories
# below it. next_cursor is set when the file page is truncated — pass it back as cursor to get the next page.
class DirectoryPage(BaseModel):
    files: list[types.FileMetadata]
    directories: list[str]
    next_cursor: str | None


# ======================================================================================================================
# server-wide metadata store: every method takes a repo name so one database can host many repositories. this is
# the lake's system of record: which content lives at which path, the full history of how it got there, and the
# manifest sequence. commit_transaction is the commit point of a transaction — implementations must make it atomic
# (all checks and updates in one storage transaction) and idempotent by txn_uuid (a retry after a lost response
# returns the original record).
class ServerMetadataStore(Protocol):

    def get_file_metadata(self, repo: str, path: str) -> types.FileMetadata | None: ...
    def list_directory(self, repo: str, prefix: str, limit: int, cursor: str | None = None) -> DirectoryPage: ...
    def get_current_seq(self, repo: str) -> int: ...
    def get_manifest(self, repo: str, seq: int) -> types.Manifest | None: ...
    def commit_transaction(self, repo: str, txn: transaction.Transaction) -> types.CommitRecord: ...
    def get_commit_record_by_txn_uuid(self, repo: str, txn_uuid: str) -> types.CommitRecord | None: ...
    def get_commit_record_by_commit_hash(self, repo: str, commit_hash: str) -> types.CommitRecord | None: ...
    def get_commit_record_by_commit_seq(self, repo: str, seq: int) -> types.CommitRecord | None: ...
    def get_commit_record_list(self, repo: str) -> list[types.CommitRecord]: ...
    def get_commit_record_page(self, repo: str, limit: int, before_seq: int | None = None) -> types.CommitHistoryPage: ...
    def register_repo(self, repo: str) -> None: ...
    def list_repos(self) -> list[str]: ...
    def store_transaction(self, repo: str, txn: transaction.Transaction) -> None: ...
    def get_transaction(self, repo: str, txn_uuid: str) -> transaction.Transaction | None: ...
    def record_uploaded_file(self, repo: str, txn_uuid: str, file: types.FileMetadata) -> None: ...
    def delete_transaction(self, repo: str, txn_uuid: str) -> None: ...
    def close(self) -> None: ...
